user  www-data;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 20M;
    sendfile        on;
    keepalive_timeout  65;
    # 允许 Cloudflare 的 IP 段作为可信代理
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/12;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;

    # 使用 CF-Connecting-IP 或 X-Forwarded-For 作为真实 IP
    #real_ip_header CF-Connecting-IP;
    # 如果 CF-Connecting-IP 不存在，可以使用 X-Forwarded-For
     real_ip_header X-Forwarded-For;

    # 可选：信任最后一个非可信 IP
    real_ip_recursive on;
    server {
        listen 3110;
        server_name localhost 127.0.0.1;
        proxy_hide_header X-Powered-By;
        fastcgi_hide_header X-Powered-By;

        root /var/www/web;
        index app.php index.html index.htm;
		location /ws/ {
		    proxy_pass http://127.0.0.1:3120;
		    proxy_http_version 1.1;
		    proxy_set_header Upgrade $http_upgrade;
		    proxy_set_header Connection "Upgrade";
		    proxy_set_header Host $host;

		    # 保持长连接配置
		    proxy_read_timeout 86400s;
		    proxy_send_timeout 86400s;
		    proxy_connect_timeout 4s;

		    # 支持WebSocket的跨域
		    add_header 'Access-Control-Allow-Origin' '*' always;
		    add_header 'Access-Control-Allow-Methods' 'GET, POST' always;
		    add_header 'Access-Control-Allow-Headers' 'X-Proxy-Verify' always;
		}
        # 处理静态资源的 location
        location / {
            try_files $uri $uri/ /app.php?$query_string;
        }


        # 处理 PHP 脚本的 location
        location ~ \.php$ {
			fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  app.php;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        # 禁止访问 .htaccess 文件
        location ~ /\.ht {
            deny all;
        }

        # 处理缓存清理等
        location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|ttf|woff|woff2)$ {
            expires 30d;
            access_log off;
            try_files $uri $uri/ =404;
        }

        # 日志配置
        error_log  /var/log/nginx/laravel_error.log;
        access_log /var/log/nginx/laravel_access.log;
    }
}
