<?php

namespace Yeskn\MainBundle\Repository;

/**
 * PostFavoritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostFavoritesRepository extends \Doctrine\ORM\EntityRepository
{
}
