<?php

namespace Yeskn\MainBundle\Repository;

/**
 * PostBlockedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostBlockedRepository extends \Doctrine\ORM\EntityRepository
{
}
