<?php

namespace Yeskn\MainBundle\Repository;

/**
 * PostThanksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostThanksRepository extends \Doctrine\ORM\EntityRepository
{
}
