services:
    Predis\Client: '@snc_redis.default'
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Yeskn\MainBundle\Twig\WebsiteInfo:
        tags:
        - { name: twig.extension }

    Yeskn\MainBundle\EventListener\RequestListener:
        tags:
        - { name: kernel.event_listener, event: kernel.request, priority: 50 }

    Yeskn\MainBundle\EventListener\ControllerListener:
        tags:
        - { name: kernel.event_listener, event: kernel.controller }

    Yeskn\MainBundle\EventListener\ResponseListener:
        tags:
        - { name: kernel.event_listener, event: kernel.response }

    Yeskn\MainBundle\EventListener\LoginListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $redis: '@snc_redis.default' # 使用 snc_redis.default 服务
        tags:
        - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    Yeskn\MainBundle\EventListener\LogoutHandler:
#        arguments:
#            $redis: '@redis'
        tags:
            - { name: 'security.logout_success_handler', firewall: 'main' }
    Yeskn\MainBundle\EventListener\UserBlockListener:
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'
            - '@router'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    Symfony\Bridge\Twig\Extension\AssetExtension: "@twig.extension.assets"
    Symfony\Bundle\SecurityBundle\Security\FirewallMap: "@security.firewall.map"
